### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by lw3259111** [ncbi-nlp/ezTag#1]
How to install the ezTag in my computer?

**Comment by biotext** [comment]
You should first set up software packages such as Ruby, Rails and MySQL to run ezTag on your computer.

For PC, follow the instructions in https://medium.com/ruby-on-rails-web-application-development/how-to-install-rubyonrails-on-windows-7-8-10-complete-tutorial-2017-fc95720ee059.

For Mac, please follow https://gorails.com/setup/osx/10.14-mojave.

You may also need to install Node.js.

After the basic setup,

1) git clone https://github.com/ncbi-nlp/ezTag.git
2) Configure config/database.yml and config/secrets.yml (run "rake secret" to get a key)
3) bundle install
4) rake db:create
5) rake db:migrate

To run ezTag,
1) rails s
2) Enter localhost:3000 on a web browser (we suggest Chrome)

Thank you.
